require("dotenv").config();
// .replace(/\\n/g, "\n")

// import { JWT } from "google-auth-library";
// import { GoogleSpreadsheet } from "google-spreadsheet";

const { JWT } = require("google-auth-library");
const { GoogleSpreadsheet } = require("google-spreadsheet");

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const doc = new GoogleSpreadsheet(
  process.env.GOOGLE_SPREADSHEET_ID,
  serviceAccountAuth
);

(async function () {
  try {
    await doc.loadInfo(); // loads document properties and worksheets
    const sheet = doc.sheetsByIndex[1];
    await sheet.getRows({
      offset: 0,
      limit: 1,
    });
    console.log("spread sheet is imported");
  } catch (err) {
    throw new Error(err);
  }
})();

module.exports = doc;
